/* ATLAS v0.1 — local-first prototype. Plain JS, no build tools required. */
'use strict';
const $=(q,root=document)=>root.querySelector(q);
const $$=(q,root=document)=>Array.from(root.querySelectorAll(q));
const uid=()=>crypto.randomUUID?.()||'id-'+Date.now()+'-'+Math.random().toString(36).slice(2);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const TWO_PI=Math.PI*2;
const COLORS={design:'#65a5ff',asbuilt:'#62eace',redline:'#ff888e'};
const TYPES={select:['↖','Select'],pan:['✥','Pan'],data:['▣','Data'],wap:['◉','WAP'],camera:['◈','Camera'],reader:['▥','Reader'],fiber:['⦿','Fiber'],coax:['⊙','Coax'],idf:['▤','TR / IDF'],sleeve:['◎','Sleeve'],pullbox:['◇','Pull Box'],note:['T','Text'],path:['⌁','Path'],cloud:['☁','Cloud'],measure:['⌑','Measure'],calibrate:['⤢','Calibrate']};
const KIND_NAME={data:'Data Outlet',wap:'Wireless Access Point',camera:'Camera',reader:'Card Reader',fiber:'Fiber Outlet',coax:'Coax Outlet',idf:'TR / IDF',sleeve:'Sleeve / Firestop',pullbox:'Pull Box',note:'Text Annotation',path:'Cable Pathway',cloud:'Revision Cloud',measure:'Field Measurement'};
const STATUSES=['planned','pulled','terminated','tested'];
const INITIAL={projectId:uid(),name:'North Tower Expansion',demo:true,floors:[],marks:[],layers:{design:true,asbuilt:true,redline:true},revision:1,createdAt:Date.now()};
let state,selectedFloorId=null,selectedId=null,mode='2d',tool='select',currentLayer='asbuilt',statusFilter='all';
let dpr=1,stageW=100,stageH=100,zoom=1,panX=0,panY=0,coord={x:0,y:0};
let paintPending=false,drag=null,pointers=new Map(),draft=[],toastTimeout=null,saveTimeout=null,editHistory=[],redoHistory=[];
let camera3D={tilt:57,angle:-25,zoom:.67},sceneDragging=null,threeTouchStart=null;
const floorImages=new Map(),pdfDocs=new Map(),thumbs=new Map(),photoUrls=new Map();
let pdfPending=null,modalHandler=null,searchText='',pendingPlacementId=null;
const DB_NAME='ATLAS_Local_Twin_v1';let dbPromise;

function db(){if(dbPromise)return dbPromise;dbPromise=new Promise((resolve,reject)=>{const req=indexedDB.open(DB_NAME,1);req.onupgradeneeded=()=>{req.result.createObjectStore('kv');req.result.createObjectStore('files')};req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)});return dbPromise}
async function dbPut(store,key,value){const d=await db();return new Promise((ok,no)=>{const tx=d.transaction(store,'readwrite');tx.objectStore(store).put(value,key);tx.oncomplete=()=>ok();tx.onerror=()=>no(tx.error)})}
async function dbGet(store,key){const d=await db();return new Promise((ok,no)=>{const r=d.transaction(store,'readonly').objectStore(store).get(key);r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error)})}
function save(){const el=$('#saveStatus');if(el)el.textContent='Saving…';clearTimeout(saveTimeout);saveTimeout=setTimeout(async()=>{try{await dbPut('kv','active',state);if($('#saveStatus'))$('#saveStatus').textContent='Saved locally'}catch(e){console.error(e);notify('Unable to save. Check browser storage space.',true)}},350)}
function snapshot(){editHistory.push(JSON.stringify(state));if(editHistory.length>40)editHistory.shift();redoHistory=[];updateUndoButtons()}
function undo(){if(!editHistory.length)return;redoHistory.push(JSON.stringify(state));state=JSON.parse(editHistory.pop());afterHistory()}
function redo(){if(!redoHistory.length)return;editHistory.push(JSON.stringify(state));state=JSON.parse(redoHistory.pop());afterHistory()}
function afterHistory(){if(!state.floors.some(f=>f.id===selectedFloorId))selectedFloorId=state.floors[0]?.id??null;selectedId=null;floorImages.clear();thumbs.clear();renderAll();save()}
function updateUndoButtons(){if($('#undoBtn'))$('#undoBtn').disabled=!editHistory.length;if($('#redoBtn'))$('#redoBtn').disabled=!redoHistory.length}
function notify(message,warn=false){let el=$('#toast');el.className='toast'+(warn?' warn':'');el.textContent=message;clearTimeout(toastTimeout);toastTimeout=setTimeout(()=>el.className='',4400)}
function byFloor(){return state.floors.find(f=>f.id===selectedFloorId)}
function markFloor(fId){return state.marks.filter(m=>m.floorId===fId)}
const isPoint=m=>m.x!=null&&m.y!=null;
function isVisible(m){return state.layers[m.layer||'asbuilt']!==false}
function fmtTime(t){return new Date(t||Date.now()).toLocaleDateString(undefined,{month:'short',day:'numeric'})}
function statusColor(s){return({tested:'#64edbc',terminated:'#a4b1ff',pulled:'#ffcb79',planned:'#8ba3ba'})[s]||'#8ba3ba'}
function shortName(f){return f?.name?.split(' · ')[0]||'Floor'}
function createDemo(){const s=structuredClone(INITIAL);s.projectId=uid();const names=['Level 01 · Main Entry','Level 02 · Surgery','Level 03 · Patient Care','Level 04 · Imaging','Level 05 · Clinical Labs','Level 06 · Mechanical'];for(let i=0;i<6;i++){const fid=uid();s.floors.push({id:fid,name:names[i],kind:'demo',demoIndex:i,level:i+1,alignX:0,alignY:0,height:14,ftPerPixel:null});const offsets=[[.18,.24],[.38,.24],[.59,.24],[.79,.24],[.19,.77],[.37,.77],[.58,.77],[.78,.77],[.49,.51],[.88,.51],[.11,.51]];offsets.forEach(([x,y],j)=>{const kind=j===8?'idf':j===9?'wap':j===10?'camera':'data';s.marks.push({id:uid(),floorId:fid,kind,x,y,label:kind==='idf'?`TR-${String(i+1).padStart(2,'0')}A`:kind==='wap'?`WAP-${i+1}A`:kind==='camera'?`CAM-${i+1}A`:`${String(i+1).padStart(2,'0')}-D-${String(j+1).padStart(3,'0')}`,size:21,color:COLORS.asbuilt,layer:'asbuilt',status:STATUSES[(j+i)%4],tr:`TR-${String(i+1).padStart(2,'0')}A`,panel:`PP-${(i%3)+1}`,port:String(j+1).padStart(2,'0'),cableId:'',notes:'Sample field record — editable',createdAt:Date.now()-j*86400000})})}return s}
function makeDemoPlan(index){const c=document.createElement('canvas');c.width=1600;c.height=1040;const x=c.getContext('2d');x.fillStyle='#101e2c';x.fillRect(0,0,c.width,c.height);
  for(let v=0;v<1600;v+=25){x.strokeStyle=v%100===0?'#3e647333':'#36586a13';x.beginPath();x.moveTo(v,0);x.lineTo(v,1040);x.stroke()}for(let v=0;v<1040;v+=25){x.strokeStyle=v%100===0?'#3e647333':'#36586a13';x.beginPath();x.moveTo(0,v);x.lineTo(1600,v);x.stroke()}
  x.textAlign='left';x.font='700 19px monospace';x.fillStyle='#87c8cf';x.fillText('ATLAS / FIELD REFERENCE',92,63);x.fillStyle='#6b8596';x.font='13px monospace';x.fillText('DEMO • NOT FOR CONSTRUCTION',1140,63);x.fillText('NTX-20'+(index+1)+'  /  REV 0'+(index+2),1210,995);
  x.strokeStyle='#6b98a8';x.lineWidth=7;x.strokeRect(130,124,1339,785);x.lineWidth=2;
  x.fillStyle='#1c3041';x.fillRect(146,455,1305,145);x.strokeStyle='#5d8191';x.lineWidth=3;x.strokeRect(146,455,1305,145);
  const topBounds=[150,400,656,910,1163,1450],bottomBounds=[150,415,695,975,1203,1450];
  function rectRoom(a,b,top,bot,label,n){x.fillStyle=n%2===0?'#152737':'#1a2e3d';x.fillRect(a,top,b-a,bot-top);x.strokeStyle='#6e9aac';x.lineWidth=3;x.strokeRect(a,top,b-a,bot-top);x.fillStyle='#819baa';x.font='15px monospace';x.textAlign='center';x.fillText(label,(a+b)/2,(top+bot)/2-9);x.font='12px monospace';x.fillStyle='#537a8b';x.fillText(`${index+1}${String(n+1).padStart(2,'0')}`,(a+b)/2,(top+bot)/2+13);
  // simple furniture, fixtures, beds
  x.strokeStyle='#416474';x.lineWidth=2;if(n%3===0){for(let k=0;k<2;k++){x.strokeRect(a+35+k*64,top+37,47,26);x.strokeRect(a+37+k*64,top+68,43,16)}}else if(n%3===1){x.strokeRect(a+45,top+48,100,40);x.beginPath();x.arc(a+170,top+65,19,0,TWO_PI);x.stroke()}else{for(let k=0;k<2;k++)x.strokeRect(a+40+k*86,top+39,67,36)} }
  const topNames=['CONSULT','NURSE STATION','OPERATING','STERILE SUPPLY','UTILITY'];const botNames=['EQUIPMENT','EXAM / PREP','WORKROOM','OFFICE','MED / IT'];for(let i=0;i<5;i++){rectRoom(topBounds[i],topBounds[i+1],143,455,topNames[(i+index)%5],i);rectRoom(bottomBounds[i],bottomBounds[i+1],600,890,botNames[(i+index)%5],i+5)}
  for(let i=0;i<6;i++){const xx=145+i*260;const lab=String.fromCharCode(65+i);x.fillStyle='#73baaf';x.beginPath();x.arc(xx,101,15,0,TWO_PI);x.fill();x.fillStyle='#0b1e2b';x.font='700 16px monospace';x.fillText(lab,xx,106);x.textAlign='center';x.fillStyle='#43738a';x.setLineDash([6,12]);x.beginPath();x.moveTo(xx,119);x.lineTo(xx,926);x.stroke();x.setLineDash([])}
  for(let i=0;i<4;i++){x.fillStyle='#75b3b3';x.font='13px monospace';x.textAlign='center';x.fillText('CORRIDOR',320+i*300,536)}
  // elevator core and stairwell
  x.fillStyle='#203c4b';x.fillRect(734,458,133,138);x.strokeStyle='#6ad4bf';x.lineWidth=2;x.strokeRect(734,458,133,138);x.textAlign='center';x.fillStyle='#91cfc9';x.font='12px monospace';x.fillText('LIFT / CORE',799,528);
  x.fillStyle='#3a6e7b';x.font='10px monospace';x.textAlign='left';x.fillText('N',1500,139);x.beginPath();x.moveTo(1507,177);x.lineTo(1507,143);x.moveTo(1507,143);x.lineTo(1499,153);x.moveTo(1507,143);x.lineTo(1515,153);x.stroke();
  x.strokeStyle='#477e86';x.lineWidth=3;x.beginPath();x.moveTo(125,981);x.lineTo(335,981);x.stroke();x.font='12px monospace';x.fillStyle='#8ba9b6';x.fillText('0',122,1004);x.fillText('50 FT',302,1004);x.textAlign='left';return c}

function template(){return `
<header class="topbar"><button class="icon-btn mobile-menu" id="mobileMenu" title="Floors" style="display:none">☰</button><div class="brand"><span class="brand-mark">⬡</span><div><div class="brand-name">ATLAS<span style="color:var(--aqua)">.</span></div><div class="brand-sub">SPATIAL INTELLIGENCE</div></div></div><div class="sep-v"></div><div class="project-identity" id="projectIdentity"><span class="bld-icon">▤</span><div><small>ACTIVE PROJECT <span id="demoBadge"></span></small><strong id="projectName"></strong></div></div><div class="top-spacer"></div><button class="search-launch" id="searchBtn" title="Search records (Ctrl+K)">⌕ <span>Search location, label, room…</span><span class="key">⌘ K</span></button><span class="top-badge"><i></i><span id="saveStatus">Saved locally</span></span><button class="icon-btn" id="undoBtn" title="Undo (Ctrl+Z)">↶</button><button class="icon-btn" id="redoBtn" title="Redo (Ctrl+Y)">↷</button><div class="sep-v"></div><button class="btn ghost" id="moreMenuBtn">⋯ <span class="hide-small">Project</span></button><button class="btn primary" id="addPdfBtn">＋ <span>Import PDFs</span></button></header>
<div class="shell"><aside class="sidebar" id="sidebar"><div class="sidebar-head"><span class="eyebrow">BUILDING LEVELS</span><span class="sidebar-count" id="floorCount">00</span></div><div class="floor-list" id="floorList"></div><button class="btn ghost" style="margin:12px 16px;font-size:11px;border-style:dashed" id="addFloorBtn">＋ Add a floor / PDF</button><div class="divider"></div><div class="sidebar-section"><div class="sidebar-section-head"><span class="eyebrow">DRAWING LAYERS</span><span style="color:#738d9e;font-size:12px">◈</span></div><div id="layerToggles"></div></div><div class="divider"></div><div class="sidebar-section"><div class="sidebar-section-head"><span class="eyebrow">FIELD WORKFLOW</span></div><div style="font-size:11px;color:#7e99ad;line-height:1.7">Place a symbol on a plan, edit its tag, and link it to its closet and port. Switch to <b style="color:#bceade">Spatial 3D</b> to navigate floors.</div></div><div class="help-box"><strong>✦ Built for the field</strong><p>Every change autosaves to this device. Export a project backup to move your work safely.</p><button id="backupSide">Export project backup ↗</button></div></aside>
<main class="workspace"><div class="workspace-top"><div class="workspace-title"><div class="floor-chip">▤</div><div><h2 id="viewTitle">Level 01 • Floor Plan</h2><div class="breadcrumb" id="breadcrumb">Project / Plan Sheets / Level 01</div></div></div><div class="workspace-controls"><div class="segmented"><button class="segment active" data-mode="2d">▧ <span>PLAN 2D</span></button><button class="segment" data-mode="3d">⬡ <span>SPATIAL 3D</span></button><button class="segment" data-mode="index">≡ <span>DROP INDEX</span></button></div><div class="mode-indicator">SYSTEM <b>● ONLINE / LOCAL</b></div></div></div>
<div class="stage" id="stage"><div class="viewer" id="viewer"><canvas id="planCanvas"></canvas></div><div class="spatial hidden" id="spatial"><div class="spatial-title"><h3>Building spatial overview</h3><p>INTERACTIVE FLOOR ASSEMBLY · 6 LEVEL MODEL</p></div><div class="spatial-orbit" id="spatialOrbit"></div><div class="spatial-help"><b>Drag</b> to orbit &nbsp; · &nbsp; <b>Scroll</b> to zoom &nbsp; · &nbsp; <b>Tap a floor</b> to open plan</div></div><div class="index-view hidden" id="indexView"></div><div class="floating-top" id="stageOverlay"><div class="plan-tag"><span class="live"></span><div><strong id="sheetName">SHEET 01 · LEVEL 01</strong><div><small id="sheetInfo">2D DRAWING · INTERACTIVE</small></div></div></div><div class="floating-tools"><button class="float-btn" id="toggleInspectorBtn" title="Toggle details panel">▥</button><button class="float-btn" id="floorSettingsBtn" title="Floor alignment and settings">⚙</button><button class="float-btn" id="fitBtn" title="Fit drawing">⤢</button></div></div><div class="bottom-left" id="stageBottomLeft"><div class="coordinate-box">X <b id="coordX">0.000</b> &nbsp; Y <b id="coordY">0.000</b></div><div class="scale-box" id="scaleText">NOT CALIBRATED</div></div><div class="bottom-right" id="stageBottomRight"><div class="zoom-control"><button id="zoomOut" title="Zoom out">−</button><span id="zoomPct">100%</span><button id="zoomIn" title="Zoom in">＋</button></div></div><div class="tool-guide hidden" id="toolGuide"></div></div>
<div class="tool-dock" id="toolDock"><div class="dock-title">TOOLS</div><div class="dock-group" id="toolSetA"></div><div class="dock-divider"></div><div class="dock-title">SYSTEMS</div><div class="dock-group" id="toolSetB"></div><div class="dock-divider"></div><div class="dock-title">AS-BUILTS</div><div class="dock-group" id="toolSetC"></div></div></main>
<aside class="inspector" id="inspector"><div class="inspector-head"><div><span class="eyebrow">CONTEXTUAL DATA</span><h3 id="inspectorHeading">Project intelligence</h3></div><button class="icon-btn" id="closeInspector" title="Toggle detail panel">⊟</button></div><div class="inspector-content" id="inspectorContent"></div></aside></div>
<div id="menuSlot"></div><div id="modalSlot"></div><input class="hidden" type="file" id="pdfInput" accept="application/pdf,.pdf" multiple><input class="hidden" type="file" id="csvInput" accept=".csv,text/csv"><input class="hidden" type="file" id="backupInput" accept=".json,.atlas"><input class="hidden" type="file" id="photoInput" accept="image/*" capture="environment">`}
function renderAll(){const app=$('#app');if(!$('#stage')){app.innerHTML=template();bindShell();}if(innerWidth<=1050&&!$('#inspector').dataset.mobileInit){$('#inspector').classList.add('hide-mobile');$('#inspector').dataset.mobileInit='1'}$('#projectName').textContent=state.name;$('#demoBadge').textContent=state.demo?'• DEMO':'';renderSidebar();renderHeader();renderTools();renderInspector();updateUndoButtons();setMode(mode);setActiveTool(tool);resizeCanvas();}
function renderHeader(){const f=byFloor();$('#viewTitle').textContent=mode==='index'?'Drop & Asset Index':mode==='3d'?'Building Spatial View':f?f.name:'No floor selected';$('#breadcrumb').textContent=mode==='3d'?'Project / Spatial Twin / Level Assembly':mode==='index'?'Project / Database / All Records':`Project / Plan Sheets / ${f?.name||'No drawing'}`;$('#sheetName').textContent=f?f.name.toUpperCase():'NO SHEET LOADED';$('#sheetInfo').textContent=f?.kind==='demo'?'DEMO REFERENCE PLAN · SELECT A SYMBOL':f?.kind==='pdf'?`SOURCE PDF · PAGE ${f.pageIndex}`:'UPLOAD A PDF TO START';$('#scaleText').textContent=f?.ftPerPixel?'SCALE CALIBRATED · '+f.ftPerPixel.toFixed(4)+' FT / PX':'NOT CALIBRATED';$$('[data-mode]').forEach(b=>b.classList.toggle('active',b.dataset.mode===mode))}
function renderSidebar(){$('#floorCount').textContent=String(state.floors.length).padStart(2,'0');$('#floorList').innerHTML=[...state.floors].reverse().map((f,i)=>`<button class="floor-item ${f.id===selectedFloorId?'selected':''}" data-floor="${esc(f.id)}"><span class="floor-number">${String(f.level??state.floors.length-i).padStart(2,'0')}</span><span class="floor-meta"><strong>${esc(f.name)}</strong><span>${f.kind==='demo'?'Reference drawing':f.kind==='pdf'?`PDF page ${f.pageIndex}`:'Drawing'} · ${markFloor(f.id).filter(m=>m.kind==='data').length} data</span></span><span class="mini-chev">›</span></button>`).join('')||`<div class="empty" style="padding:25px 4px"><strong>No floors yet</strong>Import a PDF to begin</div>`;$('#layerToggles').innerHTML=Object.entries({design:['Design','#66a4ff'],asbuilt:['Field As-Built','#58e4c9'],redline:['Redline / Revisions','#f47f8f']}).map(([k,[name,color]])=>`<label class="layer-row"><span class="layer-dot" style="background:${color}"></span>${name}<input type="checkbox" data-layer="${k}" ${state.layers[k]?'checked':''}></label>`).join('')}
function renderTools(){const groups=[['select','pan'],['data','wap','camera','reader','fiber','coax','idf'],['sleeve','pullbox','note','path','cloud','measure','calibrate']];groups.forEach((arr,j)=>{$('#toolSet'+['A','B','C'][j]).innerHTML=arr.map(t=>`<button class="tool" data-tool="${t}" title="${esc(TYPES[t][1])}"><span class="sym">${TYPES[t][0]}</span><span>${TYPES[t][1]}</span></button>`).join('')})}
function setMode(next){mode=next;$('#viewer').classList.toggle('hidden',mode!=='2d');$('#spatial').classList.toggle('hidden',mode!=='3d');$('#indexView').classList.toggle('hidden',mode!=='index');$('#stageOverlay').classList.toggle('hidden',mode!=='2d');$('#stageBottomLeft').classList.toggle('hidden',mode!=='2d');$('#stageBottomRight').classList.toggle('hidden',mode!=='2d');$('#toolDock').classList.toggle('hidden',mode==='index');renderHeader();if(mode==='2d'){resizeCanvas();loadAndDraw()}else if(mode==='3d')render3D();else renderIndex()}
function setActiveTool(t){tool=t;draft=[];$$('.tool').forEach(b=>b.classList.toggle('active',b.dataset.tool===t));$('#viewer')?.classList.toggle('pan',t==='pan');const g=$('#toolGuide');if(!g)return;if(['path','cloud','measure','calibrate'].includes(t)){const info={path:'Tap along a cable route, then select Finish.',cloud:'Drag a rectangle to cloud a revision area.',measure:'Tap two endpoints to measure a run.',calibrate:'Tap two endpoints of a known dimension.'};g.classList.remove('hidden');g.innerHTML=`<span>${info[t]}</span>${t==='path'?'<button id="finishPathBtn">Finish route ↵</button><button id="cancelPathBtn">Cancel</button>':''}`}else g.classList.add('hidden');requestPaint()}
function selectFloor(id){if(!state.floors.some(f=>f.id===id))return;selectedFloorId=id;selectedId=null;zoom=1;panX=0;panY=0;draft=[];renderSidebar();renderHeader();renderInspector();if(mode!=='2d')setMode('2d');else loadAndDraw();$('#sidebar')?.classList.remove('open')}

/* PDF / drawing pipeline. pdf.js loads on demand, only for PDF imports. */
async function loadScript(url){return new Promise((resolve,reject)=>{const s=document.createElement('script');s.src=url;s.onload=resolve;s.onerror=()=>reject(new Error('Library loading failed'));document.head.appendChild(s)})}
let pdfLoader;
async function ensurePdfJs(){if(window.pdfjsLib)return window.pdfjsLib;if(!pdfLoader)pdfLoader=(async()=>{let last;for(const host of ['https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.min.js','https://cdn.jsdelivr.net/npm/pdfjs-dist@3.11.174/build/pdf.min.js']){try{await loadScript(host);if(window.pdfjsLib){window.pdfjsLib.GlobalWorkerOptions.workerSrc=host.replace('pdf.min.js','pdf.worker.min.js');return window.pdfjsLib}}catch(e){last=e}}throw last||Error('Could not load PDF renderer. Internet is needed once to access PDF.js.');})();return pdfLoader}
async function getPdfDoc(assetKey){if(pdfDocs.has(assetKey))return pdfDocs.get(assetKey);const lib=await ensurePdfJs();const file=await dbGet('files',assetKey);if(!file)throw Error('Source PDF not found on this device. Restore a backup containing PDFs.');const data=new Uint8Array(await file.arrayBuffer());const documentPromise=lib.getDocument({data,useSystemFonts:true}).promise;pdfDocs.set(assetKey,documentPromise);try{return await documentPromise}catch(e){pdfDocs.delete(assetKey);throw e}}
async function getFloorImage(f){if(!f)return null;if(floorImages.has(f.id))return await floorImages.get(f.id);const p=(async()=>{if(f.kind==='demo')return makeDemoPlan(f.demoIndex);const doc=await getPdfDoc(f.assetKey);const pg=await doc.getPage(f.pageIndex);const vp=pg.getViewport({scale:1});const scale=Math.min(2.5,2350/Math.max(vp.width,vp.height));const view=pg.getViewport({scale});const c=document.createElement('canvas');c.width=Math.max(1,Math.ceil(view.width));c.height=Math.max(1,Math.ceil(view.height));const cx=c.getContext('2d',{alpha:false});cx.fillStyle='#fff';cx.fillRect(0,0,c.width,c.height);await pg.render({canvasContext:cx,viewport:view}).promise;return c})();floorImages.set(f.id,p);try{return await p}catch(e){floorImages.delete(f.id);throw e}}
async function loadAndDraw(){requestPaint();const f=byFloor();if(!f)return;try{await getFloorImage(f);if(f.id===selectedFloorId)requestPaint()}catch(e){notify('PDF could not be rendered: '+e.message,true);requestPaint()}}
function resizeCanvas(){const c=$('#planCanvas');if(!c)return;const r=c.parentElement.getBoundingClientRect();if(!r.width||!r.height)return;stageW=r.width;stageH=r.height;dpr=Math.min(window.devicePixelRatio||1,2);c.width=Math.round(stageW*dpr);c.height=Math.round(stageH*dpr);requestPaint()}
function requestPaint(){if(paintPending)return;paintPending=true;requestAnimationFrame(()=>{paintPending=false;drawPlan()})}
function drawingRect(img){if(!img)return{l:0,t:0,w:1,h:1};const fit=Math.min((stageW-70)/img.width,(stageH-74)/img.height);const w=img.width*fit*zoom,h=img.height*fit*zoom;return{l:(stageW-w)/2+panX,t:(stageH-h)/2+panY,w,h}}
function toWorld(sx,sy,img){if(!img)return{x:0,y:0};const r=drawingRect(img);return{x:(sx-r.l)/r.w,y:(sy-r.t)/r.h}}
function toScreen(x,y,img){const r=drawingRect(img);return{x:r.l+x*r.w,y:r.t+y*r.h}}
function drawPlan(){const c=$('#planCanvas');if(!c||mode!=='2d')return;const ctx=c.getContext('2d');ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,stageW,stageH);const f=byFloor();if(!f){drawEmpty(ctx);return}const imgPromise=floorImages.get(f.id);if(!imgPromise){getFloorImage(f).then(requestPaint).catch(()=>drawEmpty(ctx));return}Promise.resolve(imgPromise).then(img=>{if(f.id!==selectedFloorId||mode!=='2d')return;const cr=c.getContext('2d');cr.setTransform(dpr,0,0,dpr,0,0);cr.clearRect(0,0,stageW,stageH);const r=drawingRect(img);cr.shadowColor='#000a';cr.shadowBlur=25;cr.fillStyle='#ffffff';cr.fillRect(r.l-2,r.t-2,r.w+4,r.h+4);cr.shadowBlur=0;cr.drawImage(img,r.l,r.t,r.w,r.h);cr.save();cr.translate(r.l,r.t);cr.scale(r.w,r.h);for(const m of markFloor(f.id)){if(isVisible(m))drawMark(cr,m,img.width,img.height,m.id===selectedId)}drawDraft(cr,img.width,img.height);cr.restore();$('#zoomPct').textContent=Math.round(zoom*100)+'%';}).catch(e=>console.error(e))}
function drawEmpty(ctx){ctx.save();ctx.textAlign='center';ctx.fillStyle='#5fe9cd';ctx.font='58px Space Grotesk';ctx.fillText('⬡',stageW/2,stageH/2-44);ctx.font='600 23px Space Grotesk';ctx.fillStyle='#e6f6f4';ctx.fillText('Your building starts here',stageW/2,stageH/2+5);ctx.font='13px DM Sans';ctx.fillStyle='#8caaba';ctx.fillText('Import PDF plan sheets to build a navigable spatial project twin.',stageW/2,stageH/2+33);ctx.restore()}
function drawSymbol(ctx,m,x,y,rad){ctx.save();ctx.translate(x,y);const col=m.color||COLORS[m.layer]||COLORS.asbuilt;ctx.lineJoin='round';ctx.strokeStyle=col;ctx.fillStyle='#0c2031';ctx.lineWidth=2.5;ctx.shadowColor=col;ctx.shadowBlur=8;const k=m.kind;if(k==='data'){ctx.fillRect(-rad,-rad,rad*2,rad*2);ctx.strokeRect(-rad,-rad,rad*2,rad*2);ctx.beginPath();ctx.moveTo(-rad*.5,0);ctx.lineTo(rad*.5,0);ctx.moveTo(0,-rad*.5);ctx.lineTo(0,rad*.5);ctx.stroke()}else if(k==='wap'){ctx.beginPath();ctx.arc(0,0,rad,0,TWO_PI);ctx.fill();ctx.stroke();ctx.beginPath();ctx.arc(0,0,rad*.42,0,TWO_PI);ctx.stroke();}else if(k==='camera'){ctx.beginPath();ctx.moveTo(0,-rad*1.15);ctx.lineTo(rad*1.15,0);ctx.lineTo(0,rad*1.15);ctx.lineTo(-rad*1.15,0);ctx.closePath();ctx.fill();ctx.stroke();ctx.beginPath();ctx.arc(0,0,rad*.34,0,TWO_PI);ctx.stroke()}else if(k==='idf'){ctx.fillRect(-rad*1.15,-rad*1.1,rad*2.3,rad*2.2);ctx.strokeRect(-rad*1.15,-rad*1.1,rad*2.3,rad*2.2);ctx.beginPath();for(let a=-.55;a<=.56;a+=.55){ctx.moveTo(-rad*.75,a*rad);ctx.lineTo(rad*.7,a*rad)}ctx.stroke()}else if(k==='reader'){ctx.strokeRect(-rad*.8,-rad*1.15,rad*1.6,rad*2.3);ctx.fillRect(-rad*.52,-rad*.48,rad*1.04,rad*.5);ctx.strokeRect(-rad*.52,-rad*.48,rad*1.04,rad*.5)}else if(k==='fiber'){ctx.beginPath();ctx.arc(0,0,rad,0,TWO_PI);ctx.fill();ctx.stroke();ctx.beginPath();ctx.moveTo(-rad*.65,0);ctx.lineTo(rad*.65,0);ctx.moveTo(0,-rad*.65);ctx.lineTo(0,rad*.65);ctx.stroke()}else if(k==='coax'||k==='sleeve'){ctx.beginPath();ctx.arc(0,0,rad,0,TWO_PI);ctx.fill();ctx.stroke();ctx.beginPath();ctx.arc(0,0,rad*.53,0,TWO_PI);ctx.stroke()}else if(k==='pullbox'){ctx.beginPath();ctx.moveTo(0,-rad);ctx.lineTo(rad,0);ctx.lineTo(0,rad);ctx.lineTo(-rad,0);ctx.closePath();ctx.fill();ctx.stroke()}else if(k==='note'){ctx.strokeRect(-rad*.85,-rad,rad*1.7,rad*2);ctx.fillStyle=col;ctx.font=`700 ${rad*1.25}px Space Grotesk, sans-serif`;ctx.textAlign='center';ctx.textBaseline='middle';ctx.shadowBlur=0;ctx.fillText('T',0,1)}ctx.restore()}
function drawMark(ctx,m,W,H,selected=false){const col=m.color||COLORS[m.layer]||COLORS.asbuilt;const sz=clamp(Number(m.size)||21,10,75);ctx.save();ctx.globalAlpha=selected?1:.96;const isLine=['path','measure'].includes(m.kind);if(isLine){if((m.points||[]).length<2){ctx.restore();return}ctx.beginPath();m.points.forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));ctx.strokeStyle=col;ctx.lineWidth=3/W;ctx.setLineDash(m.dashed?[13/W,9/W]:[]);ctx.stroke();ctx.setLineDash([]);if(m.kind==='measure'){const a=m.points[0],b=m.points.at(-1),f=state.floors.find(fl=>fl.id===m.floorId);const v=physicalDistance(a,b,W,H,f);const label=v==null?'UNCALIBRATED':`${v.toFixed(1)} ft`;drawLabel(ctx,(a.x+b.x)/2,(a.y+b.y)/2-22/H,label,sz,W,H,col,true)}else if(m.label)drawLabel(ctx,m.points[0].x,m.points[0].y-20/H,m.label,sz,W,H,col,true);
  }else if(m.kind==='cloud'){const [a,b]=m.points||[];if(a&&b){const xx=Math.min(a.x,b.x),yy=Math.min(a.y,b.y),ww=Math.abs(b.x-a.x),hh=Math.abs(b.y-a.y);ctx.strokeStyle=col;ctx.lineWidth=3/W;ctx.setLineDash([10/W,6/W]);ctx.strokeRect(xx,yy,ww,hh);ctx.setLineDash([])}}else if(isPoint(m)){const rad=Math.max(9,sz*.65);ctx.save();ctx.translate(m.x,m.y);ctx.scale(1/W,1/H);drawSymbol(ctx,m,0,0,rad);ctx.restore();if(m.label)drawLabel(ctx,m.x,m.y+(rad+8)/H,m.label,sz,W,H,col,m.kind==='note');}if(selected){const box=markBounds(m,W,H);if(box){ctx.strokeStyle='#f4fff5';ctx.lineWidth=1.4/W;ctx.setLineDash([5/W,5/W]);ctx.strokeRect(box.l,box.t,box.w,box.h);ctx.setLineDash([])}}ctx.restore()}
function drawLabel(ctx,x,y,label,size,W,H,color,back=false){ctx.save();ctx.translate(x,y);ctx.scale(1/W,1/H);const fs=Math.max(13,size*.73);ctx.font=`700 ${fs}px 'Space Grotesk',sans-serif`;const lines=String(label).split('\n').slice(0,4);const width=Math.max(...lines.map(t=>ctx.measureText(t).width))+12;const height=lines.length*(fs+3)+6;if(back){ctx.fillStyle='#0d2029dd';ctx.fillRect(-width/2,-height/2,width,height)}ctx.fillStyle=color;ctx.textAlign='center';ctx.textBaseline='middle';ctx.shadowColor='#06121e';ctx.shadowBlur=3;lines.forEach((t,i)=>ctx.fillText(t,0,(i-(lines.length-1)/2)*(fs+3)));ctx.restore()}
function markBounds(m,W,H){if(isPoint(m)){const r=Math.max(9,(m.size||21)*.65);return{l:m.x-r/W,t:m.y-r/H,w:r*2/W,h:r*2/H}}if(m.points?.length){const xs=m.points.map(p=>p.x),ys=m.points.map(p=>p.y);return{l:Math.min(...xs)-.004,t:Math.min(...ys)-.004,w:Math.max(...xs)-Math.min(...xs)+.008,h:Math.max(...ys)-Math.min(...ys)+.008}}return null}
function drawDraft(ctx,W,H){if(draft.length===0)return;ctx.strokeStyle='#b8fbe2';ctx.lineWidth=3/W;ctx.setLineDash([8/W,5/W]);ctx.beginPath();draft.forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));ctx.stroke();ctx.setLineDash([]);draft.forEach(p=>{ctx.fillStyle='#93fff0';ctx.beginPath();ctx.arc(p.x,p.y,6/W,0,TWO_PI);ctx.fill()})}
function physicalDistance(a,b,W,H,f){return f?.ftPerPixel!=null?Math.hypot((b.x-a.x)*W,(b.y-a.y)*H)*f.ftPerPixel:null}
function hitMark(x,y,img){const candidates=markFloor(selectedFloorId).filter(isVisible).filter(m=>{if(!isPoint(m)&&!m.points)return false;if(isPoint(m))return Math.hypot((m.x-x)*img.width,(m.y-y)*img.height)<Math.max(26,(m.size||21)*1.4)/Math.max(zoom,.5);return markBounds(m,img.width,img.height)&&pointNearLine(m,{x,y},img)});return candidates.at(-1)}
function pointNearLine(m,p,img){if(!m.points?.length)return false;let min=Infinity;for(let i=1;i<m.points.length;i++){const a=m.points[i-1],b=m.points[i],vx=(b.x-a.x)*img.width,vy=(b.y-a.y)*img.height,px=(p.x-a.x)*img.width,py=(p.y-a.y)*img.height;const t=clamp((vx*px+vy*py)/(vx*vx+vy*vy||1),0,1);min=Math.min(min,Math.hypot(px-vx*t,py-vy*t))}return min<18/Math.max(zoom,.5)}
function getPosition(e){const rect=$('#planCanvas').getBoundingClientRect();return{x:e.clientX-rect.left,y:e.clientY-rect.top}}
async function pointerFloor(e){const f=byFloor();if(!f)return null;const img=await getFloorImage(f);return img}
function pointerStart(e){if(mode!=='2d')return;const c=$('#planCanvas');c.setPointerCapture?.(e.pointerId);const p=getPosition(e);pointers.set(e.pointerId,p);if(pointers.size===2){drag={type:'pinch',distance:touchDistance(),zoomStart:zoom,mid:touchMid()};return}if(e.button===1||tool==='pan'||e.shiftKey||e.code==='Space'){drag={type:'pan',sx:p.x,sy:p.y,px:panX,py:panY,moved:false};return}drag={type:tool==='cloud'?'cloud':'tap',sx:p.x,sy:p.y,moved:false,world:null};if(tool==='cloud'){const f=byFloor();if(f)getFloorImage(f).then(img=>{if(drag?.type==='cloud')draft=[toWorld(p.x,p.y,img),toWorld(p.x,p.y,img)]})}if(tool==='select'&&!pendingPlacementId){const f=byFloor();if(!f)return;getFloorImage(f).then(img=>{if(!drag||drag.type!=='tap')return;const pt=toWorld(p.x,p.y,img);const mark=hitMark(pt.x,pt.y,img);drag.world=pt;if(mark){drag.hitId=mark.id;drag.startX=mark.x;drag.startY=mark.y;drag.type='mark';drag.initial=JSON.stringify(mark);selectedId=mark.id;renderInspector();requestPaint()}else{selectedId=null;renderInspector();requestPaint()}}).catch(()=>{})}}
function touchDistance(){const a=[...pointers.values()];return a.length>1?Math.hypot(a[1].x-a[0].x,a[1].y-a[0].y):0}
function touchMid(){const a=[...pointers.values()];return a.length>1?{x:(a[0].x+a[1].x)/2,y:(a[0].y+a[1].y)/2}:a[0]||{x:0,y:0}}
function pointerMove(e){const p=getPosition(e);if(pointers.has(e.pointerId))pointers.set(e.pointerId,p);$('#coordX').textContent=coord.x.toFixed(3);$('#coordY').textContent=coord.y.toFixed(3);const f=byFloor();if(floorImages.has(f?.id)){Promise.resolve(floorImages.get(f.id)).then(img=>{const pt=toWorld(p.x,p.y,img);coord=pt;$('#coordX').textContent=pt.x.toFixed(3);$('#coordY').textContent=pt.y.toFixed(3)})}if(!drag)return;if(drag.type==='cloud'){const f=byFloor();if(f){Promise.resolve(floorImages.get(f.id)).then(img=>{if(draft.length===2){draft[1]=toWorld(p.x,p.y,img);requestPaint()}})}return}if(drag.type==='pinch'){if(pointers.size<2)return;changeZoom(clamp(drag.zoomStart*touchDistance()/Math.max(drag.distance,1),.3,6),touchMid());return}if(drag.type==='pan'){panX=drag.px+p.x-drag.sx;panY=drag.py+p.y-drag.sy;drag.moved=true;requestPaint();return}if(drag.type==='mark'){const m=state.marks.find(a=>a.id===drag.hitId);if(!m||!isPoint(m))return;if(Math.hypot(p.x-drag.sx,p.y-drag.sy)>4){drag.moved=true;const dx=(p.x-drag.sx)/Math.max(1,drag.imgW||stageW),dy=(p.y-drag.sy)/Math.max(1,drag.imgH||stageH);const f=byFloor();const img=floorImages.get(f.id);Promise.resolve(img).then(c=>{const r=drawingRect(c);m.x=clamp(drag.startX+(p.x-drag.sx)/r.w,0,1);m.y=clamp(drag.startY+(p.y-drag.sy)/r.h,0,1);requestPaint()})}return}if(drag.type==='tap'&&Math.hypot(p.x-drag.sx,p.y-drag.sy)>6){drag.type='pan';drag.px=panX;drag.py=panY;drag.sx=p.x;drag.sy=p.y}}
async function pointerEnd(e){const p=getPosition(e);pointers.delete(e.pointerId);if(!drag)return;const d=drag;drag=null;if(d.type==='pinch')return;if(d.type==='cloud'){const pts=draft.slice();draft=[];if(pts.length===2&&Math.hypot((pts[1].x-pts[0].x)*stageW,(pts[1].y-pts[0].y)*stageH)>8){addLineMark('cloud',pts);setActiveTool('select')}else notify('Drag across an area to place a cloud.',true);requestPaint();return}if(d.type==='mark'){if(d.moved){editHistory.push(JSON.stringify({...state,marks:state.marks.map(m=>m.id===d.hitId?JSON.parse(d.initial):m)}));if(editHistory.length>40)editHistory.shift();redoHistory=[];updateUndoButtons();save();renderSidebar()}return}if(d.type==='pan'||d.moved)return;const f=byFloor();if(!f)return;let img;try{img=await getFloorImage(f)}catch{return}let pt=toWorld(p.x,p.y,img);if(pt.x<0||pt.x>1||pt.y<0||pt.y>1)return;if(pendingPlacementId){const m=state.marks.find(x=>x.id===pendingPlacementId);if(m){snapshot();m.floorId=f.id;m.x=pt.x;m.y=pt.y;m.updatedAt=Date.now();selectedId=m.id;pendingPlacementId=null;renderInspector();renderSidebar();requestPaint();save();notify('Existing record linked to plan location');return}}if(tool==='select'||tool==='pan')return;
 if(tool==='path'){draft.push(pt);requestPaint();return}if(tool==='measure'||tool==='calibrate'){draft.push(pt);if(draft.length>=2){const pts=draft.slice();draft=[];if(tool==='calibrate'){openCalibration(pts,img)}else{if(!f.ftPerPixel){notify('Calibrate the plan first using the Calibrate tool.',true);setActiveTool('calibrate');draft=[pts[0]]}else{addLineMark('measure',pts);setActiveTool('select')}}}requestPaint();return}addPointMark(tool,pt)}
function pointerDouble(e){if(tool==='path'){e.preventDefault();finishPath()}}
function finishPath(){if(draft.length>=2){addLineMark('path',draft);setActiveTool('select');notify('Cable pathway saved')}else notify('Tap at least two points to draw a path.',true);draft=[];requestPaint()}
function addPointMark(kind,pt){const f=byFloor();if(!f)return;snapshot();const similar=markFloor(f.id).filter(m=>m.kind===kind);const label=kind==='data'?`${String(f.level).padStart(2,'0')}-D-${String(similar.length+1).padStart(3,'0')}`:kind==='note'?'FIELD NOTE':`${(kind||'NEW').toUpperCase()}-${String(similar.length+1).padStart(2,'0')}`;const m={id:uid(),floorId:f.id,kind,x:pt.x,y:pt.y,label,size:21,color:COLORS[currentLayer],layer:currentLayer,status:'planned',tr:'',panel:'',port:'',cableId:'',notes:'',createdAt:Date.now()};state.marks.push(m);selectedId=m.id;renderInspector();renderSidebar();requestPaint();save();notify(`${KIND_NAME[kind]||'Symbol'} placed · ${label}`)}
function addLineMark(kind,pts){snapshot();const f=byFloor();const m={id:uid(),floorId:f.id,kind,points:structuredClone(pts),label:kind==='path'?'Cable Path':kind==='cloud'?'REVISION':'',size:20,color:kind==='cloud'?COLORS.redline:COLORS[currentLayer],layer:kind==='cloud'?'redline':currentLayer,status:'planned',notes:'',dashed:false,createdAt:Date.now()};state.marks.push(m);selectedId=m.id;renderInspector();renderSidebar();requestPaint();save()}
function changeZoom(next,point={x:stageW/2,y:stageH/2}){const f=byFloor();const imgPromise=floorImages.get(f?.id);if(!imgPromise)return;Promise.resolve(imgPromise).then(img=>{const pt=toWorld(point.x,point.y,img);zoom=clamp(next,.25,9);const r=drawingRect(img);panX+=point.x-(r.l+pt.x*r.w);panY+=point.y-(r.t+pt.y*r.h);requestPaint()})}
function openCalibration(points,img){const pixels=Math.hypot((points[1].x-points[0].x)*img.width,(points[1].y-points[0].y)*img.height);openModal('Scale calibration',`<p>Enter the actual distance between the two points you selected on the drawing. Use feet to enable field distance measurements.</p><div class="field"><label>Known real-world distance (feet)</label><input id="calibrationInput" type="number" min="0.01" step="any" value="20"></div><div class="notice">Calibration is per floor. Measurements are approximate straight-line plan distances.</div>`,[{label:'Cancel',fn:closeModal},{label:'Apply calibration',primary:true,fn:()=>{const ft=Number($('#calibrationInput').value);if(!Number.isFinite(ft)||ft<=0)return notify('Enter a distance greater than zero',true);snapshot();byFloor().ftPerPixel=ft/pixels;byFloor().calibrationPts=points;save();renderHeader();closeModal();setActiveTool('measure');notify('Scale calibrated. Measure points on this floor.')}}])}

/* Contextual inspector */
function renderInspector(){const heading=$('#inspectorHeading'),box=$('#inspectorContent');if(!box)return;const m=state.marks.find(o=>o.id===selectedId);if(!m){heading.textContent='Project intelligence';renderOverview();return}heading.textContent='Element properties';const point=isPoint(m),line=['path','measure','cloud'].includes(m.kind),photo=m.photoKey;box.innerHTML=`<div class="selected-header"><div class="selected-glyph">${TYPES[m.kind]?.[0]||'◇'}</div><div style="min-width:0"><h3>${esc(m.label||KIND_NAME[m.kind])}</h3><small>${esc(KIND_NAME[m.kind]||'Markup')} · ${esc(state.floors.find(f=>f.id===m.floorId)?.name||'')}</small></div></div>
<div class="field"><label>SYMBOL / LABEL</label><input data-field="label" value="${esc(m.label||'')}" placeholder="e.g. 02-D-104"></div>
<div class="two-fields"><div class="field"><label>LAYER</label><select data-field="layer">${Object.entries({design:'Design',asbuilt:'As-Built',redline:'Redline'}).map(([k,v])=>`<option value="${k}" ${m.layer===k?'selected':''}>${v}</option>`).join('')}</select></div><div class="field"><label>STATUS</label><select data-field="status">${STATUSES.map(s=>`<option value="${s}" ${m.status===s?'selected':''}>${s[0].toUpperCase()+s.slice(1)}</option>`).join('')}</select></div></div>
<div class="field"><label>SYMBOL / TEXT COLOR & SIZE</label><div class="color-row"><input type="color" data-field="color" value="${m.color||COLORS.asbuilt}"><input type="range" min="12" max="64" step="1" data-field="size" value="${m.size||21}"><span id="textSizeOut" style="width:34px;color:#c6e2e0">${m.size||21}px</span></div></div>
${m.kind==='data'||m.kind==='fiber'||m.kind==='coax'||m.kind==='wap'||m.kind==='camera'||m.kind==='reader'?`<div class="section-label">CONNECTIVITY / ASSET DATA</div><div class="field"><label>TELECOM ROOM / IDF</label><input data-field="tr" value="${esc(m.tr||'')}" placeholder="TR-02A"></div><div class="two-fields"><div class="field"><label>PATCH PANEL</label><input data-field="panel" value="${esc(m.panel||'')}" placeholder="PP-01"></div><div class="field"><label>PORT</label><input data-field="port" value="${esc(m.port||'')}" placeholder="24"></div></div><div class="field"><label>CABLE ID / TEST REFERENCE</label><input data-field="cableId" value="${esc(m.cableId||'')}" placeholder="Identifier or test result"></div>`:''}
${line?`<div class="field"><label>LINE STYLE</label><select data-field="dashed"><option value="false" ${!m.dashed?'selected':''}>Solid line</option><option value="true" ${m.dashed?'selected':''}>Dashed line</option></select></div>`:''}
<div class="field"><label>FIELD NOTES</label><textarea data-field="notes" placeholder="Observed location, rework, site conditions…">${esc(m.notes||'')}</textarea></div><div class="section-label">PHOTO EVIDENCE</div><label class="file-btn">📷 Add site photo <input type="file" accept="image/*" capture="environment" id="markPhotoInput"></label><div id="photoHolder">${photo?'<span style="color:#819daf">Loading photo…</span>':'<p style="font-size:11px;color:#8096a8">No photo linked yet.</p>'}</div><div class="section-label">RECORD HISTORY</div><div style="font-size:11px;color:#7891a6">Created ${fmtTime(m.createdAt)} · Last modified ${fmtTime(m.updatedAt||m.createdAt)}</div>${!point&&!line?'<button class="btn primary" id="placeUnlocated" style="width:100%;margin-top:12px">⌖ Place this record on plan</button>':''}<div class="selected-actions"><button class="btn" id="copyMarkLink">⌁ Copy link</button><button class="btn" id="duplicateMark">◫ Duplicate</button><button class="btn danger" id="deleteMark">✕ Delete</button><button class="btn" id="unselectMark">✓ Done</button></div>`;
if(photo)showPhoto(photo)}
async function showPhoto(key){try{let url=photoUrls.get(key);if(!url){const blob=await dbGet('files',key);if(!blob)return;url=URL.createObjectURL(blob);photoUrls.set(key,url)}if($('#photoHolder'))$('#photoHolder').innerHTML=`<img class="photo-preview" src="${url}" alt="Site photo">`}catch(e){console.warn(e)}}
function renderOverview(){const m=state.marks,drop=m.filter(x=>x.kind==='data'),tested=drop.filter(x=>x.status==='tested').length,done=m.filter(x=>x.status==='tested').length;const total=m.filter(x=>['data','fiber','coax','wap','camera','reader'].includes(x.kind)).length;const p=total?Math.round(done/total*100):0;$('#inspectorContent').innerHTML=`<div class="overview-illustration"><div class="illus-cube">⬡</div><span>LIVE PROJECT MODEL</span></div><div class="metric-grid"><div class="metric"><strong>${state.floors.length.toString().padStart(2,'0')}</strong><small>Mapped floors</small></div><div class="metric"><strong>${total}</strong><small>Device records</small></div><div class="metric"><strong style="color:#69edce">${tested}</strong><small>Tested data drops</small></div><div class="metric"><strong>${m.length}</strong><small>Total annotations</small></div></div><div class="section-label">PROJECT INSTALLATION PULSE <span style="color:#65e8c5">${p}%</span></div><div class="status-row"><span><i class="status-dot" style="background:#849caf"></i>Planned</span><strong>${m.filter(v=>v.status==='planned').length}</strong></div><div class="status-row"><span><i class="status-dot" style="background:#ffcb79"></i>Pulled</span><strong>${m.filter(v=>v.status==='pulled').length}</strong></div><div class="status-row"><span><i class="status-dot" style="background:#a4b1ff"></i>Terminated</span><strong>${m.filter(v=>v.status==='terminated').length}</strong></div><div class="status-row"><span><i class="status-dot" style="background:#64edbc"></i>Tested</span><strong>${m.filter(v=>v.status==='tested').length}</strong></div><div class="progress-track"><span style="width:${p}%;background:linear-gradient(90deg,#2a9d8f,#6ff8cb)"></span></div><div class="section-label">RECENT FIELD ENTRIES</div>${[...m].sort((a,b)=>(b.updatedAt||b.createdAt)-(a.updatedAt||a.createdAt)).slice(0,4).map(a=>`<div class="activity-row"><span class="activity-icon">${TYPES[a.kind]?.[0]||'◇'}</span><div><strong>${esc(a.label||KIND_NAME[a.kind]||'Markup')}</strong><small>${esc(shortName(state.floors.find(f=>f.id===a.floorId)))} · ${fmtTime(a.updatedAt||a.createdAt)}</small></div></div>`).join('')||'<div class="empty">No recorded changes yet</div>'}<button class="btn" id="viewDropIndex" style="margin-top:21px;width:100%">View all database records →</button>`}
function changeSelectedField(element){const m=state.marks.find(o=>o.id===selectedId);if(!m)return;let value=element.value;const key=element.dataset.field;if(!key)return;if(key==='size')value=Number(value);if(key==='dashed')value=value==='true';if(key==='layer'&&m.color===COLORS[m.layer])m.color=COLORS[value];m[key]=value;m.updatedAt=Date.now();if(key==='size'&&$('#textSizeOut'))$('#textSizeOut').textContent=value+'px';if(key==='label'){const h=$('.selected-header h3');if(h)h.textContent=value}save();renderSidebar();requestPaint();thumbs.delete(m.floorId)}
function deleteSelected(){const m=state.marks.find(x=>x.id===selectedId);if(!m)return;snapshot();state.marks=state.marks.filter(x=>x.id!==m.id);selectedId=null;renderInspector();renderSidebar();requestPaint();save();notify('Markup deleted')}
function duplicateSelected(){const m=state.marks.find(x=>x.id===selectedId);if(!m)return;snapshot();const n=structuredClone(m);n.id=uid();n.label=n.label+' (copy)';if(isPoint(n)){n.x=clamp(n.x+.016,0,1);n.y=clamp(n.y+.016,0,1)}else if(n.points)n.points=n.points.map(p=>({x:clamp(p.x+.02,0,1),y:clamp(p.y+.02,0,1)}));n.createdAt=Date.now();state.marks.push(n);selectedId=n.id;renderInspector();renderSidebar();requestPaint();save()}
function copyMarkLink(){const m=state.marks.find(x=>x.id===selectedId);if(!m)return;const url=new URL(location.href);url.hash='mark='+encodeURIComponent(m.id);navigator.clipboard?.writeText(url.href).then(()=>notify('Record link copied. Works on devices with this project restored.')).catch(()=>notify('Unable to copy URL',true))}
function jumpToMark(id){const m=state.marks.find(x=>x.id===id);if(!m)return;selectFloor(m.floorId);selectedId=id;setActiveTool('select');renderInspector();requestPaint();if(isPoint(m)){Promise.resolve(floorImages.get(m.floorId)||getFloorImage(byFloor())).then(img=>{const pt=toScreen(m.x,m.y,img);panX+=stageW/2-pt.x;panY+=stageH/2-pt.y;requestPaint()})}}

/* Spatial navigation uses CSS 3D, intentionally zero 3D-library dependencies. */
async function makeThumb(f){if(thumbs.has(f.id))return thumbs.get(f.id);const img=await getFloorImage(f);const cn=document.createElement('canvas');cn.width=820;cn.height=570;const c=cn.getContext('2d');c.fillStyle='#132636';c.fillRect(0,0,820,570);c.drawImage(img,0,0,820,570);c.save();c.scale(820,570);for(const m of markFloor(f.id))if(isVisible(m))drawMark(c,m,img.width,img.height);c.restore();const src=cn.toDataURL('image/jpeg',.80);thumbs.set(f.id,src);return src}
async function render3D(){const orbit=$('#spatialOrbit');if(!orbit||mode!=='3d')return;const renderId=uid();orbit.dataset.render=renderId;apply3DCamera();orbit.innerHTML='';const floors=[...state.floors];let i=0,heightOffset=0;for(const f of floors){if(orbit.dataset.render!==renderId)return;const slab=document.createElement('div');slab.className='floor-slab'+(f.id===selectedFloorId?' active':'');slab.dataset.id=f.id;slab.style.transform=`translate(-50%,-50%) translate3d(${f.alignX||0}px,${f.alignY||0}px,${Math.round(heightOffset)}px)`;slab.innerHTML=`<div style="display:grid;place-items:center;width:100%;height:100%;color:#74c4c0;font-size:25px">⬡</div><div class="floor-label">${esc(shortName(f))}</div>`;orbit.appendChild(slab);makeThumb(f).then(src=>{const el=orbit.querySelector(`[data-id="${CSS.escape(f.id)}"]`);if(el)el.innerHTML=`<img src="${src}" alt="${esc(f.name)} plan"><div class="floor-label">${esc(shortName(f))}</div>`}).catch(e=>console.warn('Thumb:',e));heightOffset+=(Number(f.height)||14)/14*63;i++}$('.spatial-title p').textContent=`INTERACTIVE FLOOR ASSEMBLY · ${floors.length} LEVEL${floors.length===1?'':'S'}`}
function apply3DCamera(){const orbit=$('#spatialOrbit');if(!orbit)return;const adjusted=innerWidth<720?camera3D.zoom*.51:camera3D.zoom;orbit.style.transform=`rotateX(${camera3D.tilt}deg) rotateZ(${camera3D.angle}deg) scale(${adjusted})`}
function spatialStart(e){if(e.target.closest('.floor-slab')){threeTouchStart={x:e.clientX,y:e.clientY,id:e.target.closest('.floor-slab').dataset.id}}const element=$('#spatial');element.setPointerCapture?.(e.pointerId);sceneDragging={x:e.clientX,y:e.clientY,tilt:camera3D.tilt,angle:camera3D.angle,moved:false};}
function spatialMove(e){if(!sceneDragging)return;const dx=e.clientX-sceneDragging.x,dy=e.clientY-sceneDragging.y;if(Math.hypot(dx,dy)>5)sceneDragging.moved=true;camera3D.tilt=clamp(sceneDragging.tilt+dy*.22,18,80);camera3D.angle=sceneDragging.angle+dx*.24;apply3DCamera()}
function spatialEnd(e){const shouldClick=!!sceneDragging&&!sceneDragging.moved&&threeTouchStart?.id;const id=threeTouchStart?.id;sceneDragging=null;threeTouchStart=null;if(shouldClick&&id)selectFloor(id)}

/* Drop index / CSV. CSV inputs may contain unplaced rows. */
const csvEscape=s=>'"'+String(s??'').replace(/"/g,'""')+'"';
function downloadBlob(blob,name){const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),5000)}
function getCSV(){const cols=['floor','label','type','tr','patch_panel','port','cable_id','status','layer','x','y','notes'];return[cols.join(','),...state.marks.filter(m=>!['path','cloud','measure'].includes(m.kind)).map(m=>{const f=state.floors.find(f=>f.id===m.floorId);return[f?.name,m.label,m.kind,m.tr,m.panel,m.port,m.cableId,m.status,m.layer,m.x,m.y,m.notes].map(csvEscape).join(',')})].join('\r\n')}
function exportCSV(){downloadBlob(new Blob([getCSV()],{type:'text/csv;charset=utf-8'}),safeName(state.name)+'_drop_index.csv');notify('Drop index CSV exported')}
function csvParse(str){let fields=[],rows=[],acc='',inQuote=false;for(let i=0;i<str.length;i++){const ch=str[i];if(ch==='"'){if(inQuote&&str[i+1]==='"'){acc+='"';i++}else inQuote=!inQuote}else if(ch===','&&!inQuote){fields.push(acc);acc=''}else if((ch==='\r'||ch==='\n')&&!inQuote){if(ch==='\r'&&str[i+1]==='\n')i++;fields.push(acc);if(fields.some(x=>x!==''))rows.push(fields);fields=[];acc=''}else acc+=ch}fields.push(acc);if(fields.some(x=>x!==''))rows.push(fields);return rows}
async function importCSV(file){const rows=csvParse(await file.text());if(rows.length<2)return notify('CSV appears empty',true);const keys=rows.shift().map(k=>k.trim().toLowerCase());const get=(a,key)=>a[keys.indexOf(key)]||'';const needed=keys.includes('label')&&keys.includes('floor');if(!needed)return notify('CSV must include floor and label columns.',true);snapshot();let imported=0;for(const cells of rows){const floorString=get(cells,'floor');const f=state.floors.find(x=>x.name.toLowerCase()===floorString.toLowerCase()||shortName(x).toLowerCase()===floorString.toLowerCase());if(!f)continue;const xt=Number(get(cells,'x')),yt=Number(get(cells,'y'));const hasCoords=get(cells,'x')!==''&&get(cells,'y')!==''&&Number.isFinite(xt)&&Number.isFinite(yt)&&xt>=0&&xt<=1&&yt>=0&&yt<=1;const kind=get(cells,'type')||'data';state.marks.push({id:uid(),floorId:f.id,kind:KIND_NAME[kind]?kind:'data',label:get(cells,'label')||'UNLABELED',x:hasCoords?xt:null,y:hasCoords?yt:null,tr:get(cells,'tr'),panel:get(cells,'patch_panel'),port:get(cells,'port'),cableId:get(cells,'cable_id'),status:STATUSES.includes(get(cells,'status'))?get(cells,'status'):'planned',layer:COLORS[get(cells,'layer')]?get(cells,'layer'):'asbuilt',size:21,color:COLORS.asbuilt,notes:get(cells,'notes'),createdAt:Date.now()});imported++}save();renderSidebar();renderInspector();requestPaint();if(mode==='index')renderIndex();notify(`Imported ${imported} records. Unplaced items appear in the index.`)}
function renderIndex(){const div=$('#indexView');if(!div)return;const term=searchText.toLowerCase();const marks=state.marks.filter(m=>!['path','cloud','measure'].includes(m.kind)).filter(m=>(statusFilter==='all'||m.status===statusFilter)&&`${m.label} ${m.tr||''} ${m.panel||''} ${m.port||''} ${m.kind} ${state.floors.find(f=>f.id===m.floorId)?.name||''}`.toLowerCase().includes(term));div.innerHTML=`<div class="index-title"><div><div class="eyebrow">ASSET DATABASE / TIA-606 FRIENDLY</div><h2>Drop & Device Index</h2><p>Search identifiers, trace terminations, and navigate to a drawing location in one tap.</p></div><button class="btn primary" id="exportCSVFromIndex">↓ Export CSV</button></div><div class="metric-grid" style="grid-template-columns:repeat(4,minmax(120px,1fr));max-width:740px;margin-bottom:24px"><div class="metric"><strong>${marks.length}</strong><small>Shown records</small></div><div class="metric"><strong>${state.marks.filter(m=>m.kind==='data').length}</strong><small>Data outlets</small></div><div class="metric"><strong style="color:#80eac3">${state.marks.filter(m=>m.status==='tested').length}</strong><small>Tested records</small></div><div class="metric"><strong>${state.marks.filter(m=>m.x==null&&!m.points).length}</strong><small>Unplaced records</small></div></div><div class="index-controls"><input class="text-search" id="indexSearch" placeholder="⌕  Search all records…" value="${esc(searchText)}"><select id="statusFilter" class="text-search" style="width:155px"><option value="all">All statuses</option>${STATUSES.map(s=>`<option ${statusFilter===s?'selected':''} value="${s}">${s[0].toUpperCase()+s.slice(1)}</option>`).join('')}</select><button class="btn" id="importCSVFromIndex">↑ Import CSV</button></div><div class="table-wrap"><table class="data-table"><thead><tr><th>ASSET IDENTIFIER</th><th>FLOOR</th><th>TYPE</th><th>TR / IDF</th><th>PATCH / PORT</th><th>STATUS</th><th>LOCATION</th></tr></thead><tbody>${marks.map(m=>{const f=state.floors.find(f=>f.id===m.floorId);return`<tr data-jump="${esc(m.id)}"><td><span class="table-code">${esc(m.label||'UNLABELED')}</span></td><td>${esc(shortName(f))}</td><td>${esc(KIND_NAME[m.kind]||m.kind)}</td><td>${esc(m.tr||'—')}</td><td>${esc(m.panel||'—')} / ${esc(m.port||'—')}</td><td><span class="pill ${m.status}">${esc(m.status||'planned')}</span></td><td style="color:${isPoint(m)?'#6eebd1':'#f0bc74'}">${isPoint(m)?'⌖ View on plan':'○ Unplaced'}</td></tr>`}).join('')}</tbody></table>${marks.length?'':'<div class="empty"><strong>No matching records</strong>Import CSV or place symbols on a floor plan.</div>'}</div><p style="color:#7996a9;font-size:11px;margin:13px 0">CSV column names: floor, label, type, tr, patch_panel, port, cable_id, status, layer, x, y, notes. Coordinates are normalized 0–1.</p>`}
function safeName(s){return String(s||'ATLAS').replace(/[^a-z0-9_-]+/gi,'_').slice(0,55)}

/* Dialog / modal system */
function openModal(title,body,actions=[{label:'Close',fn:closeModal}],wide=false){const slot=$('#modalSlot');slot.innerHTML=`<div class="modal-backdrop" id="backdrop"><div class="modal ${wide?'wide':''}" role="dialog" aria-modal="true" aria-label="${esc(title)}"><div class="modal-head"><h2>${esc(title)}</h2><button class="icon-btn" id="modalClose" title="Close">✕</button></div>${body}<div class="modal-footer" id="modalFooter">${actions.map((a,i)=>`<button class="btn ${a.primary?'primary':''} ${a.danger?'danger':''}" data-modal-action="${i}">${esc(a.label)}</button>`).join('')}</div></div></div>`;modalHandler=actions;$('#modalClose').onclick=closeModal;$('#backdrop').onclick=e=>{if(e.target.id==='backdrop')closeModal()};$$('[data-modal-action]').forEach(btn=>btn.onclick=()=>modalHandler?.[Number(btn.dataset.modalAction)]?.fn())}
function closeModal(){$('#modalSlot').innerHTML='';modalHandler=null}
function newProjectDialog(){openModal('Create a new project',`<p>Start a clean digital twin. Your current project can be preserved with <b>Export project backup</b> first.</p><div class="field"><label>PROJECT NAME</label><input id="newProjectName" value="New Building Project" maxlength="100"></div><div class="notice">Creating a new project replaces the currently open workspace on this device. Existing exported backups remain intact.</div>`,[{label:'Cancel',fn:closeModal},{label:'Create project',primary:true,fn:()=>{const name=$('#newProjectName').value.trim();if(!name)return notify('Project needs a name',true);snapshot();state={projectId:uid(),name,demo:false,floors:[],marks:[],layers:{design:true,asbuilt:true,redline:true},createdAt:Date.now()};selectedFloorId=null;selectedId=null;floorImages.clear();pdfDocs.clear();thumbs.clear();mode='2d';zoom=1;panX=panY=0;save();closeModal();renderAll();notify('New project created. Import PDFs to begin.')}}])}
function requestPdfImport(){if(!state.demo)return $('#pdfInput').click();openModal('Create your building twin',`<p>You are currently exploring the six-floor sample project. Start your own project before importing real plans, or keep adding floors to the sample.</p><div class="field"><label>NEW PROJECT NAME</label><input id="pdfProjectName" value="My Building Project" maxlength="100"></div>`,[{label:'Add PDFs to demo',fn:()=>{closeModal();$('#pdfInput').click()}},{label:'New project + import',primary:true,fn:()=>{const name=$('#pdfProjectName').value.trim()||'My Building Project';snapshot();state={projectId:uid(),name,demo:false,floors:[],marks:[],layers:{design:true,asbuilt:true,redline:true},createdAt:Date.now()};selectedFloorId=null;selectedId=null;floorImages.clear();thumbs.clear();pdfDocs.clear();mode='2d';save();closeModal();renderAll();$('#pdfInput').click()}}])}
function floorSettings(){const f=byFloor();if(!f)return notify('Import a floor first.',true);openModal('Floor properties & alignment',`<p>Give the level a recognizable name. In Spatial 3D, X/Y offsets let you nudge a floor into alignment with the levels above and below.</p><div class="field"><label>FLOOR DISPLAY NAME</label><input id="floorNameInput" value="${esc(f.name)}"></div><div class="two-fields"><div class="field"><label>FLOOR NUMBER</label><input type="number" id="floorLevelInput" value="${f.level??1}"></div><div class="field"><label>SLAB HEIGHT (FT)</label><input type="number" min="1" id="floorHeightInput" value="${f.height??14}"></div></div><div class="two-fields"><div class="field"><label>3D OFFSET X (PX)</label><input type="number" step="1" id="alignXInput" value="${f.alignX||0}"></div><div class="field"><label>3D OFFSET Y (PX)</label><input type="number" step="1" id="alignYInput" value="${f.alignY||0}"></div></div><div class="notice">Prototype alignment is manual. Future CAD/IFC versions can use shared coordinates and model registration.</div>`,[{label:'Cancel',fn:closeModal},{label:'Remove floor',danger:true,fn:()=>removeFloorDialog(f.id)},{label:'Save changes',primary:true,fn:()=>{snapshot();f.name=$('#floorNameInput').value.trim()||f.name;f.level=Number($('#floorLevelInput').value)||f.level;f.height=Number($('#floorHeightInput').value)||14;f.alignX=Number($('#alignXInput').value)||0;f.alignY=Number($('#alignYInput').value)||0;state.floors.sort((a,b)=>a.level-b.level);renderSidebar();renderHeader();save();closeModal();notify('Floor properties updated')}}])}
function removeFloorDialog(id){const f=state.floors.find(x=>x.id===id);openModal('Remove floor?',`<p>This will remove <b>${esc(f?.name)}</b> and all its ${markFloor(id).length} linked records from the active project. Download a backup first if you need them.</p>`,[{label:'Cancel',fn:closeModal},{label:'Remove floor and records',danger:true,fn:()=>{snapshot();state.floors=state.floors.filter(x=>x.id!==id);state.marks=state.marks.filter(x=>x.floorId!==id);floorImages.delete(id);thumbs.delete(id);selectedFloorId=state.floors[0]?.id||null;selectedId=null;save();closeModal();renderAll()}}])}
function openSearch(){openModal('Search the spatial model',`<div class="field"><label>LABEL / TR / PATCH PANEL / ROOM</label><input id="globalSearchInput" placeholder="e.g. 02-D-003 or TR-02A" autofocus></div><div id="globalSearchResults" style="max-height:320px;overflow:auto"></div>`,[{label:'Close',fn:closeModal}],true);$('#globalSearchInput').focus();$('#globalSearchInput').addEventListener('input',searchInModal);searchInModal()}
function searchInModal(){const q=($('#globalSearchInput')?.value||'').trim().toLowerCase();const matches=state.marks.filter(m=>`${m.label} ${m.tr||''} ${m.panel||''} ${m.port||''} ${m.notes||''} ${state.floors.find(f=>f.id===m.floorId)?.name||''}`.toLowerCase().includes(q)).slice(0,30);$('#globalSearchResults').innerHTML=matches.map(m=>`<button class="btn" style="display:flex;width:100%;justify-content:space-between;margin:5px 0;text-align:left;height:auto;padding:10px" data-search-id="${esc(m.id)}"><div><strong style="display:block">${esc(m.label)}</strong><small style="color:#8aa5b3">${esc(KIND_NAME[m.kind]||m.kind)} · ${esc(state.floors.find(f=>f.id===m.floorId)?.name)}</small></div><span style="color:${isPoint(m)?'#5cebd2':'#dfa96b'}">${isPoint(m)?'⌖':'○'}</span></button>`).join('')||'<div class="empty">No matching records</div>';$$('[data-search-id]').forEach(b=>b.onclick=()=>{const id=b.dataset.searchId;closeModal();jumpToMark(id)})}
async function handlePdfUpload(files){if(!files?.length)return;try{notify('Loading PDF plan sheets…');const doc=await getDocFromFile(files[0]);pdfPending={remaining:files.slice(1)};showPdfPageChooser(doc,files[0])}catch(e){console.error(e);notify('PDF import failed: '+e.message,true)}}
async function getDocFromFile(file){const lib=await ensurePdfJs();const bytes=new Uint8Array(await file.arrayBuffer());return await lib.getDocument({data:bytes,useSystemFonts:true}).promise}
function suggestFloorName(page,n){const result=page.replace(/\.pdf$/i,'').replace(/[_-]/g,' ');return n>1?`Level ${String(n).padStart(2,'0')} · ${result}`:result}
function showPdfPageChooser(doc,file){const cap=Math.min(doc.numPages,100);const names=Array.from({length:cap},(_,i)=>{const next=state.floors.length+i+1;return`<div class="page-row"><input type="checkbox" data-pdf-page="${i+1}" ${i<16?'checked':''}><label>PAGE ${String(i+1).padStart(2,'0')}</label><input type="text" maxlength="100" data-page-name="${i+1}" value="${esc(suggestFloorName(file.name,next))}"></div>`}).join('');openModal(`Import ${esc(file.name)}`,`<p>Found <b>${doc.numPages} page${doc.numPages===1?'':'s'}</b> in this PDF. Select the sheets that represent floors, then name them. You can import other sheets later.</p><div class="import-pages">${names}</div><div style="margin-top:15px;display:flex;gap:8px"><button class="btn" id="selectAllPages">Select all</button><button class="btn" id="selectNoPages">Clear all</button></div>${doc.numPages>100?'<p class="notice">This import chooser shows the first 100 pages. Split large documents to import remaining pages.</p>':''}`,[{label:'Cancel',fn:closeModal},{label:'Import selected floors',primary:true,fn:()=>confirmPdfImport(file)}],true);$('#selectAllPages').onclick=()=>$$('[data-pdf-page]').forEach(x=>x.checked=true);$('#selectNoPages').onclick=()=>$$('[data-pdf-page]').forEach(x=>x.checked=false)}
async function confirmPdfImport(file){const selected=$$('[data-pdf-page]:checked').map(e=>({pageIndex:Number(e.dataset.pdfPage),name:$(`[data-page-name="${e.dataset.pdfPage}"]`).value.trim()}));if(!selected.length)return notify('Choose at least one page.',true);const key='pdf_'+uid();closeModal();try{await dbPut('files',key,file);snapshot();selected.forEach(({pageIndex,name},index)=>{const level=state.floors.length+1;state.floors.push({id:uid(),name:name||`Level ${String(level).padStart(2,'0')}`,kind:'pdf',assetKey:key,sourceName:file.name,pageIndex,level,height:14,alignX:0,alignY:0,ftPerPixel:null})});state.demo=false;state.floors.sort((a,b)=>a.level-b.level);if(!selectedFloorId||!state.floors.some(f=>f.id===selectedFloorId)||state.floors.some(f=>f.kind==='demo'))selectedFloorId=state.floors.at(-selected.length).id;floorImages.clear();thumbs.clear();save();renderAll();notify(`Added ${selected.length} PDF floor${selected.length!==1?'s':''}.`);await loadAndDraw();const next=pdfPending?.remaining?.shift();if(next){try{const nextDoc=await getDocFromFile(next);showPdfPageChooser(nextDoc,next)}catch(e){notify('Another PDF could not be read: '+e.message,true)}}else pdfPending=null}catch(e){notify('Unable to save PDF: '+e.message,true)}}

/* Native PDF output: multi-page JPEG-based PDF with flattened as-built markups. */
async function renderExportCanvas(f){const src=await getFloorImage(f);const canvas=document.createElement('canvas');canvas.width=src.width;canvas.height=src.height;const c=canvas.getContext('2d',{alpha:false});c.fillStyle='white';c.fillRect(0,0,canvas.width,canvas.height);c.drawImage(src,0,0);c.save();c.scale(canvas.width,canvas.height);for(const mark of markFloor(f.id))if(isVisible(mark))drawMark(c,mark,canvas.width,canvas.height);c.restore();return canvas}
const byteString=s=>new TextEncoder().encode(s);
function pdfFromJpegs(pages){const chunks=[],offsets=[0];let byteLength=0;const put=bytes=>{chunks.push(bytes);byteLength+=bytes.length};const text=s=>put(byteString(s));const obj=(id,parts)=>{offsets[id]=byteLength;text(`${id} 0 obj\n`);parts();text('\nendobj\n')};const pageIds=pages.map((_,i)=>3+i*3);text('%PDF-1.4\n%ATLAS\n');obj(1,()=>text('<< /Type /Catalog /Pages 2 0 R >>'));obj(2,()=>text(`<< /Type /Pages /Kids [${pageIds.map(id=>id+' 0 R').join(' ')}] /Count ${pages.length} >>`));pages.forEach((page,i)=>{const pageId=pageIds[i],imId=pageId+1,contentId=pageId+2;const mediaW=792,mediaH=Number((792*page.height/page.width).toFixed(2));const commands=byteString(`q\n${mediaW} 0 0 ${mediaH} 0 0 cm\n/Im0 Do\nQ\n`);obj(pageId,()=>text(`<< /Type /Page /Parent 2 0 R /MediaBox [0 0 ${mediaW} ${mediaH}] /Resources << /XObject << /Im0 ${imId} 0 R >> >> /Contents ${contentId} 0 R >>`));obj(imId,()=>{text(`<< /Type /XObject /Subtype /Image /Width ${page.width} /Height ${page.height} /ColorSpace /DeviceRGB /BitsPerComponent 8 /Filter /DCTDecode /Length ${page.data.length} >>\nstream\n`);put(page.data);text('\nendstream')});obj(contentId,()=>{text(`<< /Length ${commands.length} >>\nstream\n`);put(commands);text('endstream')})});const xref=byteLength;text(`xref\n0 ${offsets.length}\n0000000000 65535 f \n`);for(let i=1;i<offsets.length;i++)text(`${String(offsets[i]).padStart(10,'0')} 00000 n \n`);text(`trailer\n<< /Root 1 0 R /Size ${offsets.length} >>\nstartxref\n${xref}\n%%EOF`);return new Blob(chunks,{type:'application/pdf'})}
function base64Bytes(s){const binary=atob(s);const data=new Uint8Array(binary.length);for(let i=0;i<binary.length;i++)data[i]=binary.charCodeAt(i);return data}
async function exportAsBuiltPdf(){if(!state.floors.length)return notify('No floors available to export.',true);openModal('Compile as-built PDF',`<p>ATLAS will flatten the selected drawing layers, labels, routes, and symbols onto each floor sheet and download a new multi-page PDF. Your source PDFs remain unchanged.</p><div class="field"><label>DRAWING PACKAGE</label><select id="pdfScope"><option value="all">All floors (${state.floors.length} pages)</option><option value="one">Current floor only</option></select></div><div class="notice">Prototype export is a high-resolution raster PDF. For construction-grade vector PDF markups, a future edition will preserve the original PDF vector layers.</div>`,[{label:'Cancel',fn:closeModal},{label:'Generate PDF',primary:true,fn:async()=>{const scope=$('#pdfScope').value;closeModal();notify('Compiling as-built drawing package…');try{const fl=scope==='one'?[byFloor()].filter(Boolean):state.floors;const pages=[];for(const f of fl){const canvas=await renderExportCanvas(f);const jpeg=canvas.toDataURL('image/jpeg',.89).split(',')[1];pages.push({width:canvas.width,height:canvas.height,data:base64Bytes(jpeg)})}const blob=pdfFromJpegs(pages);downloadBlob(blob,`${safeName(state.name)}_AS_BUILT.pdf`);notify(`As-built PDF exported · ${pages.length} sheet${pages.length===1?'':'s'}`)}catch(e){console.error(e);notify('PDF export failed: '+e.message,true)}}}])}
async function blobToB64(blob){return await new Promise((ok,no)=>{const r=new FileReader();r.onload=()=>ok(String(r.result).split(',')[1]);r.onerror=()=>no(r.error);r.readAsDataURL(blob)})}
async function exportBackup(){notify('Building complete local project backup…');try{const keys=new Set();for(const f of state.floors)if(f.assetKey)keys.add(f.assetKey);for(const m of state.marks)if(m.photoKey)keys.add(m.photoKey);const assets=[];for(const key of keys){const blob=await dbGet('files',key);if(blob)assets.push({key,type:blob.type||'application/octet-stream',name:blob.name||null,bytes:await blobToB64(blob)})}const data={format:'ATLAS-PROJECT',version:1,exportedAt:new Date().toISOString(),project:state,assets};downloadBlob(new Blob([JSON.stringify(data)],{type:'application/json'}),`${safeName(state.name)}.atlas.json`);notify(`Backup exported (${assets.length} embedded files). Keep it safe.`)}catch(e){console.error(e);notify('Backup failed: '+e.message,true)}}
async function restoreBackup(file){try{const obj=JSON.parse(await file.text());if(obj.format!=='ATLAS-PROJECT'||!obj.project||!Array.isArray(obj.project.floors)||!Array.isArray(obj.project.marks)||!Array.isArray(obj.assets))throw Error('Not a valid ATLAS backup');openModal('Restore project backup',`<p>Restore <b>${esc(obj.project.name)}</b> with ${obj.project.floors.length} floors, ${obj.project.marks.length} markups, and ${obj.assets.length} original files?</p><div class="notice">This replaces your active workspace, so export a backup first if you need it.</div>`,[{label:'Cancel',fn:closeModal},{label:'Restore backup',primary:true,fn:async()=>{try{closeModal();for(const a of obj.assets){if(!a.key||!a.bytes)continue;const blob=new Blob([base64Bytes(a.bytes)],{type:a.type||'application/octet-stream'});await dbPut('files',a.key,blob)}snapshot();state=obj.project;state.layers||={design:true,asbuilt:true,redline:true};selectedFloorId=state.floors[0]?.id||null;selectedId=null;floorImages.clear();pdfDocs.clear();thumbs.clear();zoom=1;panX=panY=0;mode='2d';save();renderAll();notify('Project successfully restored.')}catch(e){notify('Restore failed: '+e.message,true)}}}])}catch(e){notify('Invalid backup: '+e.message,true)}}
function exportCSVTemplate(){const txt='floor,label,type,tr,patch_panel,port,cable_id,status,layer,x,y,notes\n"Level 01","01-D-001","data","TR-01A","PP-01","01","","planned","asbuilt","0.45","0.60","Example entry"\n';downloadBlob(new Blob([txt],{type:'text/csv'}),'atlas_import_template.csv')}

function openMenu(){const slot=$('#menuSlot');if(slot.innerHTML){slot.innerHTML='';return}slot.innerHTML=`<div class="menu" id="projectMenu"><button data-menu="new">◫ &nbsp; New empty project</button><button data-menu="demo">⬡ &nbsp; Open six-floor demo</button><button data-menu="rename">✎ &nbsp; Rename project</button><div style="height:1px;background:var(--line);margin:6px 0"></div><button data-menu="pdf">▧ &nbsp; Export as-built PDF</button><button data-menu="csv">≡ &nbsp; Export drop index CSV</button><button data-menu="template">⇩ &nbsp; Download CSV template</button><button data-menu="importcsv">⇧ &nbsp; Import CSV records</button><div style="height:1px;background:var(--line);margin:6px 0"></div><button data-menu="backup">⬇ &nbsp; Export project backup</button><button data-menu="restore">↻ &nbsp; Restore project backup</button><button data-menu="about">ⓘ &nbsp; About local storage</button></div>`}
function handleMenuAction(key){$('#menuSlot').innerHTML='';if(key==='new')return newProjectDialog();if(key==='pdf')return exportAsBuiltPdf();if(key==='csv')return exportCSV();if(key==='template')return exportCSVTemplate();if(key==='importcsv')return $('#csvInput').click();if(key==='backup')return exportBackup();if(key==='restore')return $('#backupInput').click();if(key==='rename')return openModal('Rename project',`<div class="field"><label>NAME</label><input id="renameProject" value="${esc(state.name)}"></div>`,[{label:'Cancel',fn:closeModal},{label:'Save name',primary:true,fn:()=>{state.name=$('#renameProject').value.trim()||state.name;save();renderHeader();$('#projectName').textContent=state.name;closeModal()}}]);if(key==='demo')return openModal('Load demo project',`<p>Explore ATLAS with six synthetic floor plans and sample labeled outlets, WAPs, cameras and telecom rooms.</p><div class="notice">This replaces your active project. Export a backup first if you need to keep it.</div>`,[{label:'Cancel',fn:closeModal},{label:'Load demo',primary:true,fn:()=>{snapshot();state=createDemo();selectedFloorId=state.floors[1].id;selectedId=null;floorImages.clear();pdfDocs.clear();thumbs.clear();mode='2d';zoom=1;panX=panY=0;save();closeModal();renderAll();notify('Six-floor sample building opened.')}}]);if(key==='about')return openModal('About your ATLAS data',`<p><b>Local-first:</b> plan PDF files, photos, locations, and records are stored in your browser's IndexedDB on this device, not uploaded to this GitHub Pages website.</p><p><b>Backups are important:</b> browser cleanup, private mode, device changes, or website origin changes may remove access to local records. Export an ATLAS backup after each field session.</p><p><b>Sharing:</b> a copied record link works only if that record is available in the opened project's local database. Multi-user syncing and account permissions are planned, not included here.</p><p><b>3D:</b> the spatial view stacks your PDF floor sheets as interactive slabs; it is not BIM geometry, a measured architectural model, or a substitute for verified design documents.</p>`,[{label:'Got it',fn:closeModal}])}

/* Global UI events. A single delegated handler survives view refreshes. */
function bindShell(){document.addEventListener('click',async e=>{const t=e.target;
  const floor=t.closest('[data-floor]');if(floor)return selectFloor(floor.dataset.floor);
  const modeBtn=t.closest('[data-mode]');if(modeBtn)return setMode(modeBtn.dataset.mode);
  const toolBtn=t.closest('[data-tool]');if(toolBtn)return setActiveTool(toolBtn.dataset.tool);
  const menu=t.closest('[data-menu]');if(menu)return handleMenuAction(menu.dataset.menu);
  const jump=t.closest('[data-jump]');if(jump)return jumpToMark(jump.dataset.jump);
  if(t.closest('#moreMenuBtn'))return openMenu();if(t.closest('#addPdfBtn')||t.closest('#addFloorBtn'))return requestPdfImport();
  if(t.closest('#searchBtn'))return openSearch();if(t.closest('#backupSide'))return exportBackup();if(t.closest('#floorSettingsBtn'))return floorSettings();if(t.closest('#toggleInspectorBtn'))return $('#inspector').classList.toggle('hide-mobile');
  if(t.closest('#fitBtn')){zoom=1;panX=panY=0;requestPaint();return}
  if(t.closest('#zoomIn'))return changeZoom(zoom*1.2);if(t.closest('#zoomOut'))return changeZoom(zoom/1.2);
  if(t.closest('#undoBtn'))return undo();if(t.closest('#redoBtn'))return redo();if(t.closest('#closeInspector'))return $('#inspector').classList.toggle('hide-mobile');if(t.closest('#mobileMenu'))return $('#sidebar').classList.toggle('open');
  if(t.closest('#finishPathBtn'))return finishPath();if(t.closest('#cancelPathBtn'))return setActiveTool('select');
  if(t.closest('#placeUnlocated')){pendingPlacementId=selectedId;setMode('2d');setActiveTool('select');notify('Tap the plan to locate this imported record.');return}if(t.closest('#unselectMark')){selectedId=null;renderInspector();requestPaint();return}if(t.closest('#deleteMark'))return deleteSelected();if(t.closest('#duplicateMark'))return duplicateSelected();if(t.closest('#copyMarkLink'))return copyMarkLink();if(t.closest('#viewDropIndex'))return setMode('index');
  if(t.closest('#exportCSVFromIndex'))return exportCSV();if(t.closest('#importCSVFromIndex'))return $('#csvInput').click();
  if($('#projectMenu')&&!t.closest('#projectMenu'))$('#menuSlot').innerHTML='';
});
$('#pdfInput').addEventListener('change',e=>{const f=[...e.target.files];e.target.value='';handlePdfUpload(f)});
$('#csvInput').addEventListener('change',e=>{if(e.target.files[0])importCSV(e.target.files[0]);e.target.value='' });
$('#backupInput').addEventListener('change',e=>{if(e.target.files[0])restoreBackup(e.target.files[0]);e.target.value=''});
document.addEventListener('change',e=>{const t=e.target;if(t.matches('[data-layer]')){state.layers[t.dataset.layer]=t.checked;save();requestPaint();thumbs.clear();if(mode==='3d')render3D();return}if(t.matches('[data-field]'))changeSelectedField(t);if(t.id==='markPhotoInput'&&t.files[0])attachPhoto(t.files[0]);if(t.id==='statusFilter'){statusFilter=t.value;renderIndex()}});
document.addEventListener('input',e=>{const t=e.target;if(t.id==='indexSearch'){searchText=t.value;const p=t.selectionStart;renderIndex();$('#indexSearch').focus();$('#indexSearch').setSelectionRange(p,p);return}if(t.matches('[data-field="size"],[data-field="color"]'))changeSelectedField(t)});
const canvas=$('#planCanvas');canvas.addEventListener('pointerdown',pointerStart);canvas.addEventListener('pointermove',pointerMove);canvas.addEventListener('pointerup',pointerEnd);canvas.addEventListener('pointercancel',e=>{pointers.delete(e.pointerId);drag=null});canvas.addEventListener('dblclick',pointerDouble);canvas.addEventListener('contextmenu',e=>{e.preventDefault();if(tool==='path')finishPath()});canvas.addEventListener('wheel',e=>{e.preventDefault();const p=getPosition(e);changeZoom(zoom*(e.deltaY>0?.88:1.12),p)},{passive:false});
const scene=$('#spatial');scene.addEventListener('pointerdown',spatialStart);scene.addEventListener('pointermove',spatialMove);scene.addEventListener('pointerup',spatialEnd);scene.addEventListener('pointercancel',()=>{sceneDragging=null;threeTouchStart=null});scene.addEventListener('wheel',e=>{e.preventDefault();camera3D.zoom=clamp(camera3D.zoom*(e.deltaY>0?.9:1.1),.25,2.0);apply3DCamera()},{passive:false});
window.addEventListener('resize',()=>{resizeCanvas();apply3DCamera();$('#mobileMenu').style.display=innerWidth<720?'grid':'none';if(innerWidth>1050)$('#inspector').classList.remove('hide-mobile')});$('#mobileMenu').style.display=innerWidth<720?'grid':'none';
document.addEventListener('keydown',e=>{if(e.key==='Escape'){if($('#backdrop'))closeModal();else{setActiveTool('select');selectedId=null;renderInspector();requestPaint()}}if(e.target.closest('input,textarea,select'))return;if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();openSearch()}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();undo()}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='y'){e.preventDefault();redo()}if(e.key==='Enter'&&tool==='path'){finishPath()}});
window.addEventListener('hashchange',openHashMark);}
async function attachPhoto(file){const m=state.marks.find(o=>o.id===selectedId);if(!m)return;try{const key='photo_'+uid();await dbPut('files',key,file);snapshot();m.photoKey=key;m.updatedAt=Date.now();save();renderInspector();notify('Photo attached to field record')}catch(e){notify('Photo storage failed: '+e.message,true)}}
function openHashMark(){const match=location.hash.match(/^#mark=(.+)$/);if(!match)return;const id=decodeURIComponent(match[1]);if(state.marks.some(x=>x.id===id))jumpToMark(id)}

async function boot(){try{state=await dbGet('kv','active');if(!state?.floors||!state?.marks){state=createDemo();await dbPut('kv','active',state)}state.layers||={design:true,asbuilt:true,redline:true};selectedFloorId=state.floors[1]?.id||state.floors[0]?.id||null;$('#app').innerHTML=template();bindShell();renderAll();loadAndDraw();openHashMark();if(!sessionStorage.getItem('atlasIntroShown')){sessionStorage.setItem('atlasIntroShown','1');setTimeout(()=>notify('Welcome to ATLAS · Demo loaded. Select any symbol or explore Spatial 3D.'),1100)}}catch(e){console.error('ATLAS start failure:',e);$('#app').innerHTML='<div class="loading-screen"><span class="brand-glyph">⚠</span><h1>Storage unavailable</h1><p>Use a normal browser window on an HTTPS site. IndexedDB is required.</p></div>'}}
boot();
